// Metadata forensics ported from Sieve (MIT):
// https://github.com/Phineas1500/sieve-ai-image-detector
// A structural marker short-circuits the model at 0.99. Markers count only
// inside the containers that actually carry them.

export type MetadataHit = {
  hit: boolean;
  reason?: string;
};

function ascii(value: string): Uint8Array {
  const out = new Uint8Array(value.length);
  for (let i = 0; i < value.length; i++) out[i] = value.charCodeAt(i) & 0xff;
  return out;
}

const C2PA_MARKERS = [
  {
    pat: ascii('http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia'),
    reason: 'c2pa:trainedAlgorithmicMedia',
  },
  {
    pat: ascii('compositeWithTrainedAlgorithmicMedia'),
    reason: 'c2pa:compositeWithTrainedAlgorithmicMedia',
  },
];

function indexOfBytes(hay: Uint8Array, pat: Uint8Array): number {
  const last = hay.length - pat.length;
  const first = pat[0];
  outer: for (let i = 0; i <= last; i++) {
    if (hay[i] !== first) continue;
    for (let j = 1; j < pat.length; j++) {
      if (hay[i + j] !== pat[j]) continue outer;
    }
    return i;
  }
  return -1;
}

function sniffC2PA(data: Uint8Array): MetadataHit | null {
  for (const { pat, reason } of C2PA_MARKERS) {
    if (indexOfBytes(data, pat) !== -1) return { hit: true, reason };
  }
  return null;
}

const PNG_SIG = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];

function keyword(data: Uint8Array, length: number): string {
  let value = '';
  const n = Math.min(length, 80);
  for (let i = 0; i < n; i++) value += String.fromCharCode(data[i] ?? 0);
  return value;
}

function sniffPNG(bytes: Uint8Array, cap: number): MetadataHit {
  let offset = PNG_SIG.length;
  while (offset + 12 <= cap) {
    const len =
      ((bytes[offset]! << 24) |
        (bytes[offset + 1]! << 16) |
        (bytes[offset + 2]! << 8) |
        bytes[offset + 3]!) >>>
      0;
    const type = String.fromCharCode(
      bytes[offset + 4]!,
      bytes[offset + 5]!,
      bytes[offset + 6]!,
      bytes[offset + 7]!,
    );
    if (type === 'IEND') break;
    const data = bytes.subarray(offset + 8, Math.min(offset + 8 + len, cap));
    if (type === 'tEXt' || type === 'iTXt') {
      const nul = data.indexOf(0);
      if (nul > 0) {
        const kw = keyword(data, nul);
        if (kw === 'parameters') return { hit: true, reason: 'png:sd-parameters' };
        if (kw === 'prompt' || kw === 'workflow') {
          const json = data[nul + 1] === 0x7b && data[nul + 2] === 0x22;
          if (type === 'iTXt' || json) return { hit: true, reason: `png:comfyui-${kw}` };
        }
        if (type === 'iTXt' && kw === 'XML:com.adobe.xmp') {
          const c2pa = sniffC2PA(data);
          if (c2pa) return c2pa;
        }
      }
    }
    if (type === 'caBX') {
      const c2pa = sniffC2PA(data);
      if (c2pa) return c2pa;
    }
    offset += 12 + len;
  }
  return { hit: false };
}

function sniffJPEG(bytes: Uint8Array, cap: number): MetadataHit {
  let offset = 2;
  while (offset + 4 <= cap) {
    if (bytes[offset] !== 0xff) break;
    const marker = bytes[offset + 1]!;
    if (marker === 0xff) {
      offset++;
      continue;
    }
    if (marker === 0xd9 || marker === 0xda) break;
    if (marker >= 0xd0 && marker <= 0xd8) {
      offset += 2;
      continue;
    }
    const len = (bytes[offset + 2]! << 8) | bytes[offset + 3]!;
    if (len < 2) break;
    if (marker === 0xeb || marker === 0xe1) {
      const c2pa = sniffC2PA(bytes.subarray(offset + 4, Math.min(offset + 2 + len, cap)));
      if (c2pa) return c2pa;
    }
    offset += 2 + len;
  }
  return { hit: false };
}

export function sniffMetadata(bytes: Uint8Array): MetadataHit {
  const cap = Math.min(bytes.length, 524288);
  if (bytes.length >= 16 && PNG_SIG.every((value, index) => bytes[index] === value)) {
    return sniffPNG(bytes, cap);
  }
  if (bytes.length >= 4 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    return sniffJPEG(bytes, cap);
  }
  return { hit: false };
}

export function metadataDetail(reason: string): string {
  switch (reason) {
    case 'c2pa:trainedAlgorithmicMedia':
      return "The file's content credentials say it was created with a trained model.";
    case 'c2pa:compositeWithTrainedAlgorithmicMedia':
      return "The file's content credentials say it includes AI-generated media.";
    case 'png:sd-parameters':
      return 'The PNG metadata includes Stable Diffusion generation parameters.';
    default:
      if (reason.startsWith('png:comfyui-')) {
        return 'The PNG metadata includes a ComfyUI workflow.';
      }
      return "The file's metadata says it was generated by AI.";
  }
}
